ALTER TABLE IF EXISTS ticket_configs ALTER COLUMN channel_id DROP NOT NULL;
ALTER TABLE IF EXISTS ticket_configs ALTER COLUMN channel_id SET DEFAULT NULL;
ALTER TABLE IF EXISTS ticket_configs ALTER COLUMN category_id DROP NOT NULL;
ALTER TABLE IF EXISTS ticket_configs ALTER COLUMN category_id SET DEFAULT NULL;
ALTER TABLE IF EXISTS ticket_configs ALTER COLUMN support_role_id DROP NOT NULL;
ALTER TABLE IF EXISTS ticket_configs ALTER COLUMN support_role_id SET DEFAULT NULL;
